# service.yaml
# Purpose: Ping ClusterIP Service
# depends_on: [deployment.yaml]

apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: app
  labels:
    app: ping
spec:
  type: ClusterIP
  selector:
    app: ping
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
